### ISSUE TITLE
Output filenames make it hard to write build-scripts for certain compilers

### ISSUE THREAD

**Issue by pngwjpgh** [timbertson/gup#11]
Some compilers (notably [pandoc](http://pandoc.org)) rely on the extension of the target-filename to determine behaviour.

Taken from pandocs manpage:

> To produce a PDF, specify an output file with a .pdf extension. […]
> 
> `pandoc test.txt -o test.pdf`

I propose either:
  - using a prefix `out.<filename>` instead of a suffix `<filename>.out`
  - building some more logic to generate `<basename>.out.<extension>`

I have basic knowledge of python and would be willing to contribute patches if needed.

**Comment by timbertson** [comment]
Great point, I hadn't thought of that. The only trouble I can see is we'd need to _also_ change the other suffixes to prefixes - so that you couldn't get some weird case where you have an outfile for `foo.lock` called out.**foo.lock** and a lockfile for `out.foo` called **out.foo**.lock. It's an edge case, but it's probably best to be consistent anyway.

And in fact, changing them all at once makes it pretty simple. Here's a branch, I'll merge once I've had a chance to do some proper testing: https://github.com/timbertson/gup/pull/12
